#!/usr/bin/bash
if [[ "$#" -lt 1 ]]; then
  echo "Usage: $0 name [args...]"
  exit 1
fi

name="$1"
shift

docker run -it \
  --name "${name}" \
  -v $(pwd):/host \
  --user "$(id -u):$(id -g)" \
  "vitreusx/pas-cg:latest" \
  $@

docker rm "${name}" 1>/dev/null